-- Phase 2: finance schema
create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  account_type text not null check (account_type in ('bank', 'debt')),
  starting_balance numeric not null default 0
);

create table if not exists public.recurring_rules (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  amount numeric not null,
  is_income boolean not null default false,
  category text,
  interval_every int not null default 1,
  interval_unit text not null check (interval_unit in ('days', 'weeks', 'months', 'years')),
  start_date date not null,
  end_date date,
  account_id bigint references public.accounts(id) on delete set null,
  counterparty text,
  last_materialized_date date
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  amount numeric not null,
  date date not null,
  account_id bigint references public.accounts(id) on delete set null,
  counterparty text,
  is_income boolean not null default false,
  recurring_rule_id bigint references public.recurring_rules(id) on delete set null,
  category text
);

create table if not exists public.finance_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  onboarded_at timestamptz,
  last_expense_prompt_date date
);

create index if not exists accounts_user_id_idx on public.accounts(user_id);
create index if not exists recurring_rules_user_id_idx on public.recurring_rules(user_id);
create index if not exists transactions_user_id_date_idx on public.transactions(user_id, date);
create index if not exists transactions_recurring_rule_id_idx on public.transactions(recurring_rule_id);

alter table public.accounts enable row level security;
alter table public.recurring_rules enable row level security;
alter table public.transactions enable row level security;
alter table public.finance_profiles enable row level security;

drop policy if exists "accounts_own" on public.accounts;
drop policy if exists "recurring_rules_own" on public.recurring_rules;
drop policy if exists "transactions_own" on public.transactions;
drop policy if exists "finance_profiles_own" on public.finance_profiles;
create policy "accounts_own" on public.accounts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "recurring_rules_own" on public.recurring_rules for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "transactions_own" on public.transactions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "finance_profiles_own" on public.finance_profiles for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Phase 3: health schema
create table if not exists public.health_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  goal_type text not null check (goal_type in ('lose_weight', 'maintain', 'gain_weight')),
  current_weight numeric,
  protein_goal numeric,
  carbs_goal numeric,
  fat_goal numeric,
  calories_goal numeric,
  onboarded_at timestamptz,
  last_checkin_prompt_date date
);

create table if not exists public.health_daily_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null,
  energy_morning smallint,
  energy_midday smallint,
  energy_night smallint,
  mood_morning smallint,
  mood_midday smallint,
  mood_night smallint,
  activity text,
  unique (user_id, log_date)
);

create table if not exists public.health_meals (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  daily_log_id bigint not null references public.health_daily_logs(id) on delete cascade,
  meal_type text not null check (meal_type in ('breakfast', 'lunch', 'dinner', 'snack')),
  description text,
  protein numeric,
  carbs numeric,
  fat numeric,
  calories numeric
);

create table if not exists public.health_weight_goals (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  target_weight numeric not null,
  target_date date not null,
  reward text,
  hit boolean not null default false
);

create table if not exists public.health_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  event_date date not null,
  notes text,
  is_deadline boolean not null default false
);

create index if not exists health_daily_logs_user_date_idx on public.health_daily_logs(user_id, log_date);
create index if not exists health_meals_daily_log_id_idx on public.health_meals(daily_log_id);
create index if not exists health_weight_goals_user_id_idx on public.health_weight_goals(user_id);
create index if not exists health_events_user_date_idx on public.health_events(user_id, event_date);

alter table public.health_profiles enable row level security;
alter table public.health_daily_logs enable row level security;
alter table public.health_meals enable row level security;
alter table public.health_weight_goals enable row level security;
alter table public.health_events enable row level security;

drop policy if exists "health_profiles_own" on public.health_profiles;
drop policy if exists "health_daily_logs_own" on public.health_daily_logs;
drop policy if exists "health_meals_own" on public.health_meals;
drop policy if exists "health_weight_goals_own" on public.health_weight_goals;
drop policy if exists "health_events_own" on public.health_events;
create policy "health_profiles_own" on public.health_profiles for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "health_daily_logs_own" on public.health_daily_logs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "health_meals_own" on public.health_meals for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "health_weight_goals_own" on public.health_weight_goals for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "health_events_own" on public.health_events for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
