-- Health day log v2: food items, sleep, weight, exercise, overall mood

alter table public.health_daily_logs
  add column if not exists mood_overall numeric,
  add column if not exists sleep_hours numeric,
  add column if not exists weight numeric;

alter table public.health_meals
  add column if not exists energy smallint;

-- One meal section row per type per day
create unique index if not exists health_meals_log_type_uidx
  on public.health_meals (daily_log_id, meal_type);

create table if not exists public.health_meal_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  meal_id bigint not null references public.health_meals(id) on delete cascade,
  description text not null,
  sort_order int not null default 0
);

create index if not exists health_meal_items_meal_id_idx
  on public.health_meal_items (meal_id);

create table if not exists public.health_exercises (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  daily_log_id bigint not null references public.health_daily_logs(id) on delete cascade,
  activity_type text not null,
  duration_minutes numeric,
  sort_order int not null default 0
);

create index if not exists health_exercises_daily_log_id_idx
  on public.health_exercises (daily_log_id);

alter table public.health_meal_items enable row level security;
alter table public.health_exercises enable row level security;

drop policy if exists "health_meal_items_own" on public.health_meal_items;
drop policy if exists "health_exercises_own" on public.health_exercises;

create policy "health_meal_items_own" on public.health_meal_items
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "health_exercises_own" on public.health_exercises
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
