-- Phase 2 finance schema: accounts, recurring rules, transactions, profiles
-- Safe to re-run (IF NOT EXISTS / drop+create policies).

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  account_type text not null check (account_type in ('bank', 'debt')),
  starting_balance numeric not null default 0
);

create table if not exists public.recurring_rules (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  amount numeric not null,
  is_income boolean not null default false,
  category text,
  interval_every int not null default 1,
  interval_unit text not null check (interval_unit in ('days', 'weeks', 'months', 'years')),
  start_date date not null,
  end_date date,
  account_id bigint references public.accounts(id) on delete set null,
  counterparty text,
  last_materialized_date date
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  amount numeric not null,
  date date not null,
  account_id bigint references public.accounts(id) on delete set null,
  counterparty text,
  is_income boolean not null default false,
  recurring_rule_id bigint references public.recurring_rules(id) on delete set null,
  category text
);

create table if not exists public.finance_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  onboarded_at timestamptz,
  last_expense_prompt_date date
);

create index if not exists accounts_user_id_idx on public.accounts(user_id);
create index if not exists recurring_rules_user_id_idx on public.recurring_rules(user_id);
create index if not exists transactions_user_id_date_idx on public.transactions(user_id, date);
create index if not exists transactions_recurring_rule_id_idx on public.transactions(recurring_rule_id);

alter table public.accounts enable row level security;
alter table public.recurring_rules enable row level security;
alter table public.transactions enable row level security;
alter table public.finance_profiles enable row level security;

drop policy if exists "accounts_own" on public.accounts;
drop policy if exists "recurring_rules_own" on public.recurring_rules;
drop policy if exists "transactions_own" on public.transactions;
drop policy if exists "finance_profiles_own" on public.finance_profiles;

create policy "accounts_own" on public.accounts
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "recurring_rules_own" on public.recurring_rules
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "transactions_own" on public.transactions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "finance_profiles_own" on public.finance_profiles
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
